# GNU_INSTALL_ROOT ?= /usr/local/gcc-arm-none-eabi-6-2017-q2-update/bin/
# GNU_VERSION ?= 6.3.1
GNU_INSTALL_ROOT ?= /usr/local/Cellar/arm-none-eabi-gcc/10.3-2021.07/bin/
GNU_VERSION ?= 11.3.rel1
GNU_PREFIX ?= arm-none-eabi
